[package]
name = "kadr-media"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
kadr-core = { path = "../core" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
tempfile.workspace = true
kadr-analysis = { path = "../analysis" }
